all:
  hosts:
    zu1:
      ansible_host: 185.81.167.215
      ansible_user: cuse
      ansible_port: 22
      ansible_ssh_private_key_file: "/home/cuse/.ssh/id_rsa"
      ansible_sudo_pass: "{{ sudo_password }}"
      #ansible_password: "{{ host_password }}"
