---
# https://blog.ssdnodes.com/blog/secure-ansible-playbook/

- name: Maintain Server

  # Specify the hosts you want to target
  hosts: zu1
  become: true
  vars_prompt:
    - name: sudo_password
      prompt: enter remote password
      private: true
      confirm: false
  vars:
    ansible_user: cuse
    username: cuse
    public_key: "{{ lookup('file', '/home/cuse/.ssh/id_rsa_vps.pub') }}"
  roles:
    - packages
    - ufw
    - fail2ban
    - ssh
