---
# https://blog.ssdnodes.com/blog/secure-ansible-playbook/

- name: Maintain Server

  # Specify the hosts you want to target
  hosts: zu1
  become: true
  
  vars:
    ansible_user: cuse
    username: cuse
    public_key: "{{ lookup('file', '/home/cuse/.ssh/id_rsa.pub') }}"
  
  vars_prompt:
    - name: sudo_password
      prompt: enter remote sudo password (not root pass)
      private: yes
      confirm: no

  roles:
    - packages
    - ssh
    - ufw
    - fail2ban
