---
# https://blog.ssdnodes.com/blog/secure-ansible-playbook/

- name: Provision a new server with hardened SSH and basic iptables.

  # Specify the hosts you want to target
  hosts: zu1
  remote_user: root
  become: true

  vars_prompt:
    - name: username
      prompt: enter user name
      private: no
      confirm: no

    - name: user_password
      prompt: enter password
      private: yes
      encrypt: sha512_crypt
      confirm: yes
      salt_size: 7

  vars:
    public_key: "{{ lookup('file', '/home/cuse/.ssh/id_rsa.pub') }}"
    UserKnownHostsFile: ""

  roles:
    - user
    - packages
    - ssh
    - iptables
    - ufw
