---
# https://blog.ssdnodes.com/blog/secure-ansible-playbook/

- name: Provision a new server with hardened SSH and basic iptables.

  # Specify the hosts you want to target
  hosts: zu1
  become: true
  vars_prompt:
    - name: ansible_sudo_pass
      prompt: enter remote sudo password
      # Don't show the chars when typing
      private: true
      confirm: false
    - name: user_password
      prompt: enter password for new user
      private: true
      encrypt: sha512_crypt
      confirm: false
      salt_size: 7

  vars:
    public_key: "{{ lookup('file', '/home/cuse/.ssh/id_rsa_vps.pub') }}"
    ansible_user: root
    ansible_ssh_private_key_file: "/home/cuse/.ssh/id_rsa_vps"
    username: cuse

  roles:
    - user
    - packages
    - ufw
    - fail2ban
    - ssh
