- name: Stats
  hosts: all
  gather_facts: true
  tasks:
    - name: Debug Gathered Facts
      ansible.builtin.debug:
        var: item
      with_items:
        - "{{ ansible_lsb }}"
        - "{{ ansible_default_ipv4 }}"
        - "{{ ansible_date_time }}"
        - "{{ ansible_dns }}"
        - "{{ ansible_env }}"
        - "{{ ansible_hostname }}"
        - "{{ ansible_memory_mb }}"
        - "{{ ansible_memfree_mb }}"
      debug:
        var: item

    - name: Capture OS Name
      ansible.builtin.command: uname -a
      register: os_name
      changed_when: false

    - name: Debug OS Name
      ansible.builtin.debug:
        var: os_name.stdout
