matches:

  # https://github.com/dysfunc/ascii-emoji

  - trigger: ":shrug"
    replace: "¯\\_(ツ)_/¯"
  - trigger: ":angryemo"
    replace: "ಠ_ಠ"
  - trigger: ":trollemo"
    replace: "( ͡° ͜ʖ ͡°)"
  - trigger: ":tableflipemo"
    replace: "(╯°□°）╯︵ ┻━┻"
  - trigger: ":scaredshrugemo"
    replace: "¯\\_(⊙︿⊙)_/¯"
  - trigger: ":exhaspemo"
    replace: "t(-_-t)"
  - trigger: ":loveeyesemo"
    replace: "♥‿♥"
  - trigger: ":blowkissemo"
    replace: "( ˘ ³˘)♥ "
  - trigger: ":singemo"
    replace: "ヾ(´〇`)ﾉ♪♪♪"
  - trigger: ":happybearemo"
    replace: "(ᵔᴥᵔ)"
  - trigger: ":pointemo"
    replace: "(☞ﾟヮﾟ)☞"
  - trigger: ":ashamedemo"
    replace: "(._.)"
  - trigger: ":sunglassesemo"
    replace: |
      ( •_•)
      ( •_•)>⌐■-■
      (⌐■_■)

  - trigger: ":boxico"
    replace: "□"
  - trigger: ":tickico"
    replace: "✓"
  - trigger: ":starico"
    replace: "☆"
  - trigger: ":crossico"
    replace: "❌"
  - trigger: ":tickinboxico"
    replace: "✅"
  - trigger: ":crossinboxico"
    replace: "☒"
  - trigger: ":heartico"
    replace: "♥"
  - trigger: ":handpointico"
    replace: "☞"
  - trigger: ":arrowico"
    replace: "→"
  
  - trigger: ":grinning face:"
    replace: "😀"
  
  - trigger: ":grinning face with sweat:"
    replace: "😅"
  
  - trigger: ":face with tears of joy:"
    replace: "😂"
  
  - trigger: ":thinking face:"
    replace: "🤔"
    
  - trigger: ":rolling on the floor laughing:"
    replace: "🤣"
    
  - trigger: ":tired face:"
    replace: "😫"