matches:
    # Accents
  - trigger: "n``"
    replace: "ñ"
  - trigger: "N``"
    replace: "Ñ"
  - trigger: "a``"
    replace: "á"
  - trigger: "e``"
    replace: "é"
  - trigger: "i``"
    replace: "í"
  - trigger: "o``"
    replace: "ó"
  - trigger: "u``"
    replace: "ú"
  - trigger: "A``"
    replace: "Á"
  - trigger: "E``"
    replace: "É"
  - trigger: "I``"
    replace: "Í"
  - trigger: "O``"
    replace: "Ó"
  - trigger: "U``"
    replace: "Ú"
  - trigger: "?``"
    replace: "¿"
  - trigger: "!``"
    replace: "¡"

  - trigger: "degreeico"
    replace: "°"
  - trigger: "halfdimico"
    replace: "Ø"
  - trigger: "flatico"
    replace: "♭"
  - trigger: "sharpico"
    replace: "♯"
  - trigger: "naturalico"
    replace: "♮"
    
  - trigger: "eurico"
    replace: "€"