- name: Ensure wheel group is present
  ansible.builtin.group:
    name: wheel
    state: present
- name: Ensure wheel group has sudo privileges
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL:ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"
- name: Install the `sudo` package
  ansible.builtin.package:
    name: sudo
    state: present
- name: Create the non-root user account
  ansible.builtin.user:
    name: "{{ username }}"
    password: "{{ user_password }}"
    shell: /bin/bash
    update_password: on_create
    groups: wheel
    append: true
