# https://alacritty.org/config-alacritty.html
# https://github.com/alacritty/alacritty-theme

[window]
decorations = "full"
padding = { x = 2, y = 2 }

[font]
size = 14.0

[font.bold]
family = "Cascadia Code NF"
style = "Bold"

[font.bold_italic]
family = "Cascadia Code NF"
style = "Bold Italic"

[font.italic]
family = "Cascadia Code NF"
style = "Italic"

[font.normal]
family = "Cascadia Code NF"
style = "Light"

[keyboard]
bindings = [
   { key = "Return", mods = "Control", action = "SpawnNewInstance" }
]

# Colors (Alabaster Dark)
# author tonsky

[colors.primary]
background = '#0E1415'
foreground = '#CECECE'

[colors.cursor]
text = '#0E1415'
cursor = '#CECECE'

[colors.normal]
black = '#0E1415'
red = '#e25d56'
green = '#73ca50'
yellow = '#e9bf57'
blue = '#4a88e4'
magenta = '#915caf'
cyan = '#23acdd'
white = '#f0f0f0'

[colors.bright]
black = '#777777'
red = '#f36868'
green = '#88db3f'
yellow = '#f0bf7a'
blue = '#6f8fdb'
magenta = '#e987e9'
cyan = '#4ac9e2'
white = '#FFFFFF'