version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my_database
    restart: always
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: