matches:

  # - trigger: ":test"
  #   replace: "{{output}}"
  #   vars:
  #     - name: output
  #       type: script
  #       params:
  #         args:
  #           - python
  #           - "%CONFIG%/scripts/os.py"

  - triggers: [":date", "shortdate"]
    replace: "{{datestamp}}"
    vars:
      - name: datestamp
        type: date
        params:
          format: "%Y%m%d"
          
  - trigger: ":altdate"
    replace: "{{date}}"
    label: "01/01/1970"
    vars:
      - name: date
        type: date
        params:
          format: "%d/%m/%Y"
  - trigger: ":altdate"
    replace: "{{date}}"
    label: "Thursday, 1 January 1970"
    vars:
      - name: date
        type: date
        params:
          format: "%A, %d %B, %Y"

  # Print the output of a shell command
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"


  - trigger: ":revpra"
    replace: "**praise**: "
  - trigger: ":revnit"
    replace: "**nitpick**: "
  - trigger: ":revsug"
    replace: "**suggestion**: "
  - trigger: ":reviss"
    replace: "**issue**: "
  - trigger: ":revtod"
    replace: "**todo**: "
  - trigger: ":revque"
    replace: "**question**: "
  - trigger: ":revtho"
    replace: "**thought**: "
  - trigger: ":revcho"
    replace: "**chore**: "
  - trigger: ":revtyp"
    replace: "**typo**: "
  - trigger: ":revpol"
    replace: "**polish**: "
  - trigger: ":revqui"
    replace: "**quibble**: "

  - trigger: ":quote"
    replace: "{{output}}"
    vars:
      - name: output
        type: choice
        params:
          values:
            - "Every moment is a fresh beginning."
            - "Everything you can imagine is real."
            - "Whatever you do, do it well."

  - trigger: ":mdlink"
    replace: "[$|$]({{clipboard}})"
    vars:
      - name: "clipboard"
        type: "clipboard"