- name: Install the `fail2ban` package
  package:
    name: fail2ban
    state: latest
    
- name: Copy Fail2Ban local config
  template:
    src: jail.local.j2  # The name of your template file
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'

- name: Reload Fail2Ban config
  systemd:
    name: fail2ban
    state: reloaded